routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/login', [AuthController::class, 'login'])->name('login');
Route::post('/login', [AuthController::class, 'handleLogin'])->name('login.handle');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

Route::get('/', [HomeController::class, 'index'])->name('index')->middleware('auth');
Route::resource('user', UserController::class)->middleware('auth.admin');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'last_name',
        'phone_number',
        'is_admin',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function youtubeHistorySearch()
    {
        return $this->hasMany(YoutubeHistorySearch::class);
    }
}

app/Models/YoutubeHistorySearch.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class YoutubeHistorySearch extends Model
{
    use HasFactory;

    public $fillable = ['user_id', 'term'];
}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    public function login()
    {
        return view('login');
    }

    public function handleLogin(Request $request)
    {
        $credentials = ['email' => $request->email, 'password' => $request->password];

        if (Auth::attempt($credentials)) {
            $request->session()->regenerate();

            return redirect()->intended('/');
        }

        return back()->withErrors([
            'email' => 'The provided credentials do not match our records.',
        ])->onlyInput('email');
    }

    public function logout(Request $request)
    {
        Auth::logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect()->route('login');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\YoutubeHistorySearch;
use Google\Service\YouTube;
use Google_Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    public function index(Request $request)
    {
        $page_name = 'Vídeos';
        try {
            YoutubeHistorySearch::create(['term' => $request->q, 'user_id' => Auth::user()->id]);
            $DEVELOPER_KEY = 'AIzaSyDQf4EojkJJUeMDpOEK12cZZ7SNLudvoA4';

            $client  = new Google_Client();
            $client->setDeveloperKey($DEVELOPER_KEY);

            $youtube = new YouTube($client);

            $searchResponse = $youtube->search->listSearch('id,snippet', array(
                'q' => $request->q,
                'maxResults' => $request->maxResults,
            ));

            $collection = collect($searchResponse->items);

            return view('index', ['page_name' => $page_name, 'collection' => $collection]);

        } catch (\Exception $e) {
            return view('index', ['page_name' => $page_name]);
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $page_name = "Usuários";
        $users = User::all();
        return view('user.index', array('users' => $users, 'page_name' => $page_name));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {

        $route = route('user.store');
        $page_name = "Novo Usuário";


        return view('user.create', array('route' => $route,  'page_name' => $page_name));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {

        try {

            $user = User::create([
                'name' => $request->name,
                'last_name' => $request->last_name,
                'phone_number' => $request->phone_number,
                'is_admin' => $request->is_admin,
                'email' => $request->email,
                'password' => Hash::make($request->password)
            ]);

            return redirect()->route('user.index')->with('success', 'Usuário criado com sucesso!');
        } catch (\Exception) {

            return redirect('user.index')->with('error', 'Erro ao tentar criar usuário. Não se preocupe, nossa equipe foi notificada.');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(User $user)
    {
        $user->where('id', $user->id)->get();
        $route = route('user.update', $user->id);
        $page_name = "Editar Usuário";

        return view('user.create', array('user' => $user, 'route' => $route, 'page_name' => $page_name));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, User $user)
    {
        try {
            User::where('id', $user->id)->update([
                'name' => $request->name,
                'last_name' => $request->last_name,
                'phone_number' => $request->phone_number,
                'is_admin' => $request->is_admin,
                'email' => $request->email,
                'password' => Hash::make($request->password)
            ]);

            return redirect()->route('user.index')->with('success', 'Usuário alterado com sucesso!');


            return view('user.create');
        } catch (\Exception $e) {

            return redirect()->route('user.index')->with('error', 'Erro ao tentar alterar usuário. Não se preocupe, nossa equipe foi notificada.');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(User $user)
    {
        try {

            User::destroy($user->id);

            return redirect()->route('user.index')->with('success', 'Usuário removido com sucesso!');


            return view('user.create');
        } catch (\Exception $e) {

            return redirect()->route('user.index')->with('error', 'Erro ao tentar remover usuário. Não se preocupe, nossa equipe foi notificada.');
        }
    }
}

resources/views/index.blade.php
@extends('layout.base')

@section('content')
<section class="content-header">
    <div class="container-fluid">
    <h2 class="text-center display-4">Buscar vídeos</h2>
    </div>

    </section>
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <form action="/" method="GET">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="maxResults">Quantidade</label>
                            <select name="maxResults" id="maxResults" class="form-control">
                                <option value="5">5</option>
                                <option value="10">10</option>
                                <option value="15">15</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group input-group-lg">
                        <input type="search" class="form-control form-control-lg" placeholder="Digite o termo para busca"
                            name="q" />
                        <div class="input-group-append">
                            <a href="#" class="btn btn-lg btn-default" id="handle_search">
                                <i class="fa fa-search"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    @isset($items)
        <div class="row">
            <div class="col-lg-10 offset-md-1">
                <div class="card" style="position: relative; left: 0px; top: 0px;">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fab fa-youtube"></i>
                            Vídeos
                        </h3>
                    </div>
                    <div class="card-body">
                        @foreach ($items->chunk(4) as $chunk)
                            <div class="row mb-5">
                                @foreach ($chunk as $item)
                                    <div class="col-lg-3">
                                        <img src="{{ $item->snippet->thumbnails->medium->url }}" alt="">
                                        <h5>{{ $item->snippet->title }}</h5>
                                    </div>
                                @endforeach
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    @endisset
@endsection

resources/views/layout/base.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PlayLab vídeos</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('css/adminlte.min.css') }}">
</head>

<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i
                            class="fas fa-bars"></i></a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">




                <li class="nav-item">
                    <a class="nav-link" href="{{ route('logout') }}">
                        Sair <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="/" class="brand-link">
                <span class="brand-text font-weight-light"><strong>PlayLab</strong> vídeos</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="{{ asset('img/user2-160x160.jpg') }}" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">{{ Auth::user()->name . ' ' . Auth::user()->last_name }}</a>
                    </div>
                </div>

                <!-- SidebarSearch Form -->
                <div class="form-inline">

                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a href="{{ route('index') }}"
                                class="nav-link {{ request()->routeIs('index') ? 'active' : null }}">
                                <i class="nav-icon fab fa-youtube"></i>
                                <p>
                                    Vídeos
                                </p>
                            </a>
                        </li>
                        @if (Auth::user()->is_admin == 1)
                            <li class="nav-item {{ request()->routeIs('user.*') ? 'menu-open' : null }} ">
                                <a href="#" class="nav-link {{ request()->routeIs('user.*') ? 'active' : null }}">
                                    <i class="nav-icon fas fa-tachometer-alt"></i>
                                    <p>
                                        Usuários
                                        <i class="right fas fa-angle-left"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="{{ route('user.index') }}"
                                            class="nav-link {{ request()->routeIs('user.index') ? 'active' : null }}">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Listar Usuários</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ route('user.create') }}"
                                            class="nav-link {{ request()->routeIs('user.create') ? 'active' : null }}">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Criar usuário</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">{{ isset($page_name) ? $page_name : null }}</h1>
                        </div><!-- /.col -->

                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    @yield('content')
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->

        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                Anything you want
            </div>
            <!-- Default to the left -->
        </footer>
    </div>
    <!-- ./wrapper -->

    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
    <!-- Bootstrap 4 -->
    <script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('js/adminlte.min.js') }}"></script>

</body>

</html>

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Log in</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="css/adminlte.min.css">
</head>

<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="/"><b>PlayLab</b> | vídeos</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Autentique-se para iniciar a sessão.</p>

                <form action="{{ route('login.handle') }}" method="post">
                    @csrf
                    <div class="input-group mb-3">
                        <input type="email" class="form-control" placeholder="E-mail" name="email">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Password" name="password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-8">

                        </div>
                        <!-- /.col -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>
    <!-- /.login-box -->

    <!-- jQuery -->
    <script src="plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="js/adminlte.min.js"></script>
</body>

</html>

resources/views/user/create.blade.php
@extends('layout.base')

@section('content')
    <div class="col-md-8 offset-2">


        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Informações do usuário</h3>
            </div>

            <form method="POST" action="{{ $route }}">
                @csrf
                @isset($user)
                    @method('put')
                @endisset
                <div class="card-body">
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label for="name">Primeiro nome</label>
                                <input type="text" class="form-control" placeholder="Ex: João" name="name" required
                                    value="{{ isset($user) ? $user->name : null }}">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="last_name">Sobrenome</label>
                                <input type="text" class="form-control" placeholder="Ex: Silva" name="last_name" required
                                    value="{{ isset($user) ? $user->last_name : null }}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <div class="form-group">
                                <label for="phone_number">Telefone</label>
                                <input type="text" class="form-control" placeholder="(11)1234-5678" name="phone_number"
                                    required value="{{ isset($user) ? $user->phone_number : null }}">
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <label for="is_admin">Permissão</label>
                                <select name="is_admin" id="is_admin" class="form-control" required>
                                    <option value="0" {{ isset($user) && $user->is_admin == 0 ? 'selected' : null }}>
                                        Comum
                                    </option>
                                    <option value="1" {{ isset($user) && $user->is_admin == 1 ? 'selected' : null }}>
                                        Administrador</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label for="email">E-mail</label>
                                <input type="email" class="form-control" placeholder="joao.silva@email.com.br" required
                                    name="email" value="{{ isset($user) ? $user->email : null }}">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="password">Senha</label>
                                <input type="password" class="form-control" placeholder="****" required name="password"
                                    value="">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>

            </form>
        </div>


    </div>
@endsection

resources/views/user/index.blade.php
@extends('layout.base')

@section('content')
    <div class="col-md-12">


        @if (session()->has('success'))
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h5><i class="icon fas fa-check"></i> Muito bom!</h5>
                {{ session('success') }}
            </div>
        @endif
        @if (session('error'))
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h5><i class="icon fas fa-check"></i> Ops...</h5>
                {{ session('error') }}
            </div>
        @endif

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Usuários cadastrados</h3>
            </div>

            <div class="card-body p-0">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>Nome completo</th>
                            <th>E-mail</th>
                            <th>Telefone</th>
                            <th>Permissão</th>
                            <th>Data de cadastro</th>
                            <td style="width: 15%"></td>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($users as $user)
                            <tr>
                                <td>{{ $user->id }}</td>
                                <td>{{ $user->name . ' ' . $user->last_name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->phone_number }}</td>
                                <td>{{ $user->type == 0 ? 'Comum' : 'Admin' }}</td>
                                <td>{{ $user->created_at }}</td>
                                <td>
                                    <a href="{{ route('user.edit', $user->id) }}" class="btn btn-primary btn-xs"><i
                                            class="fas fa-user-edit"></i>
                                        Editar</a>
                                    <form action="{{ route('user.destroy', $user->id) }}" method="POST" style="display: inline-block">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger btn-xs"><i class="fas fa-trash"></i>
                                            Excluir</button>
                                    </form>

                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="7" class="text-center">Nenhum usuário cadastrado ainda :(</td>
                            </tr>
                        @endforelse


                    </tbody>
                </table>
            </div>

        </div>
    </div>
@endsection